### ISSUE TITLE
Are we giving 2nd dose to people who has been confirm positive?

### ISSUE THREAD

**Issue by garyyeap** [MoH-Malaysia/covid19-public#161]
<img width="570" alt="圖片" src="https://user-images.githubusercontent.com/798943/132855674-f40384bf-a1c0-48e2-9318-0f20f17329e7.png">
Weird records from `linelist_deaths.csv`. Can anyone explain this?

**Comment by Hazwang** [comment]
Once you've recovered from covid and no symptoms. We should wait for a few weeks to go ahead and complete the vaccination. This is highly recommended for those who had a very mild to asymptomatic infection.

**Comment by chez1978** [comment]
I am actually surprised there are so many breakthrough deaths, unless there
is an error of different definition or classification, am not sure how it
can be 0.009%

**Comment by garyyeap** [comment]
@Hazwang If you mean these cases are 2nd Infection after recovered then they should update the positive_date to the second positive date.

**Comment by sylye** [comment]
> @Hazwang If you mean these cases are 2nd Infection after recovered then they should update the positive_date to the second positive date.

Exactly. I found this weird data as well. The 'positive date' should reflect the last time she  tested positive if she infected twice. For the record highlighted by @MrBarbie, the Melaka 66 years lady , impossible the patient diagnosed on 5/19, and then only died on 8/6, and just 3 days before she still could go to take vaccine on 8/3. She should have died not due to the 5/19 infection, but a second infection. So the 'date positive' should be the second infection. The data doesn't make sense.

**Comment by chez1978** [comment]
Referring to the CovidNow portal, Dr Maheshwara, who is also the Crisis
Preparedness and Response Centre head of data said reported deaths are
based on the day the case was announced to the public.

So far, this is the data the health ministry has been reporting, he said,
adding that actual deaths are based on the true date of death.

"In Malaysia, we report deaths 'due to' Covid, rather than deaths 'with'
Covid.

"Due to Covid means clinical investigation has found that cause of death
(CoD) was Covid.

"Death 'with' Covid means the patient was Covid+ at time of death (or a
short period before).

"We focus on deaths 'due to' Covid because it is important to have the
correct number for analysis of vaccine effectiveness and case fatality rate.

"However, this takes time, because it requires autopsy and clinical audit
(rather than just checking if the patient is Covid+)."

The health ministry, he said decided to report on backlogged data to the
Malaysian public to ensure transparency about the death numbers.

"But, it is also vital for us to have a proper picture of the trend - in
Klang Valley, deaths are clearly going down, not up (as expected with high
vaccination percentage).

"Therefore, the health ministry made a decision to be transparent about
both numbers. We are being very clear how many were reported.

"However, we are also categorising the reported cases according to the true
date of death, so the rakyat and policymakers can get a proper picture."

Covid-19: Backlogged death reports due to manpower constraints
<https://www.nst.com.my/news/nation/2021/09/726522/covid-19-backlogged-death-reports-due-manpower-constraints>

Note to Self: Time to cross-check the numbers and dates with the ones
announced to the public previously. Do we have confirmation these are the
ACTUAL date of death?

**Comment by chez1978** [comment]
[image: image.png]

**Comment by MrBarbie** [comment]
It still doesnt address the problem being discussed here though. We have been going on the assumption that "date" is date of death rather than date they report the death (which makes no sense). BUT **no confirmation** that it is actual date of death.
If "date" is the date when the death is reported or not the date of death, then where is this all important information: the date of death
