### ISSUE TITLE
No explanation for new colums

### ISSUE THREAD

**Issue by hajime651118** [MoH-Malaysia/covid19-public#170]
- deaths_malaysia.csv and deaths_state.csv
deaths_new ...  numbers in report
deaths_new_dod  ... numbers on the day
deaths_bid  ... numbers of BID in report
deaths_bid_dod  ... numbers of BID on the day

- linelist
date_positive  ... date of positive
date_dose1  ... 2nd vaccination date
date_dose2   ... 2nd vaccination date
vaxtype   ... s for Sinovax, p for Pyzer, u for ???
state
age  ... Age
male  ...  1 for male, 0 for female
bid  ... 1 with BID, 0 without it
malaysian  ... 1 for Malaysian, 0 for non Malaysian
comorb  ... 1 with comorbidity, 0 without it

- aefi
date ... Statistics date
vaxtype  ... s for Sinovax, p for Pyzer, u for ???
doses  ... Actual Vaccinated dose (Pending?)
reports_mysj  ...  ???
reports_npra  ...  ???
nonserious  ... non serious side effect
serious  ... serious side effect
suspected_anaphylaxis  ... suspected anaphylaxis
acute_facial_paralysis  ... acute_facial paralysis
venous_thromboembolism  ... venous thromboembolism
myo_pericarditis  ... myo pericarditis

**Comment by NobodyButMe-Haiya** [comment]
good . but myself i also don't know what to updated anymore. inconsstent.  i rather  push people to covid19 portal for now

**Comment by chez1978** [comment]
I think explained in this press article.

Covid-19: Backlogged death reports due to manpower constraints
<https://www.nst.com.my/news/nation/2021/09/726522/covid-19-backlogged-death-reports-due-manpower-constraints>

Referring to the CovidNow portal, Dr Maheshwara, who is also the Crisis
Preparedness and Response Centre head of data said reported deaths are
based on the day the case was announced to the public.

So far, this is the data the health ministry has been reporting, he said,
adding that actual deaths are based on the true date of death.

"In Malaysia, we report deaths 'due to' Covid, rather than deaths 'with'
Covid.

"Due to Covid means clinical investigation has found that cause of death
(CoD) was Covid.

"Death 'with' Covid means the patient was Covid+ at time of death (or a
short period before).

"We focus on deaths 'due to' Covid because it is important to have the
correct number for analysis of vaccine effectiveness and case fatality rate.

"However, this takes time, because it requires autopsy and clinical audit
(rather than just checking if the patient is Covid+)."

The health ministry, he said decided to report on backlogged data to the
Malaysian public to ensure transparency about the death numbers.

"But, it is also vital for us to have a proper picture of the trend - in
Klang Valley, deaths are clearly going down, not up (as expected with high
vaccination percentage).

"Therefore, the health ministry made a decision to be transparent about
both numbers. We are being very clear how many were reported.

"However, we are also categorising the reported cases according to the true
date of death, so the rakyat and policymakers can get a proper picture."

Consider rectified I hope.

[image: image.png]

**Comment by mnyunus** [comment]
Excellent list, thanks!

"vaxtype ... s for Sinovax, p for Pyzer, u for ???"

u = most lkely 'unknown'.
a = AstraZeneca.

Btw Covid Now uses the term "Daily Actual Deaths (7d average)" which gave 99 for Malaysia yesterday.
I'm struggling to understand what actual raw data they are using, since 99 looks inconsistent with any of the deaths data fields.

**Comment by junxian428** [comment]
DOD = Dead/died of disease. ?

**Comment by mnyunus** [comment]
Looks like 'Dead on the Day'.
No explanation on Github.

ny

**Comment by hajime651118** [comment]
Unknown can be possible because few vaccine clinical trials are undergoing.
