### ISSUE TITLE
Pending VMS sync (lineset.csv)

### ISSUE THREAD

**Issue by hajime651118** [MoH-Malaysia/covid19-public#177]
2021-06-30,2021-06-20,2021-06-17,,Pending VMS sync,Sarawak,55,1,0,1,1

another 11 lines are same issue.

**Comment by mnyunus** [comment]
I just rename them as 'unknown' in my dashboard, haha!

**Comment by mnyunus** [comment]
From CITF:
pending = doses delivered that are 'quarantined' in the Vaccine Management System due to errors and/or inconsistencies in vaccine bar code, batch number, et cetera; these problems are usually resolved soon and affect ~0.1% of all records on a rolling basis. pending records for dates far in the past are not unresolved errors, but rather reflect backdated manual uploads.

**Comment by hajime651118** [comment]
Thank you.
