### ISSUE TITLE
Total Clusters - DG (5447) vs GitHub (5448)

### ISSUE THREAD

**Issue by SayangiSabah-TimmyLu** [MoH-Malaysia/covid19-public#193]
it has been certain period, i noticed that there's a variance of 1 cluster recorded between Director General of Health and GitHub data.
![asdfsafasdfsaf](https://user-images.githubusercontent.com/91001273/135202536-b5c9f121-8049-4b06-b23f-ae2b94090ad6.png)

**Comment by KennethThePro** [comment]
From what I see there is no discrepancy of the number of clusters. The total clusters are 5447. The reason it is 5448 in the file is because the first row is the name of columns as shown in the picture below. Those are just line numbers and don't really correspond to the number of data rows

![image](https://user-images.githubusercontent.com/86338269/135214983-492514db-7d0f-444a-a081-1e95b8e04404.png)

**Comment by SayangiSabah-TimmyLu** [comment]
oh... the first row being use for as remarks @ represent each in between stands for what.

Thanks for clarified.

**Comment by SayangiSabah-TimmyLu** [comment]
oh... the first row being use for as remarks @ represent each in between stands for what.

Thanks for clarified.
