### ISSUE TITLE
Inconsistent number of deaths for unvaccinated individuals

### ISSUE THREAD

**Issue by KennethThePro** [MoH-Malaysia/covid19-public#195]
A simple count of unvaccinated individual in the linelist_death yields 18268 (by calculating the numbers of rows that has no vaccine type) while the state_deaths total yields a total of 18319 unvaccinated deaths (by calculating new_deaths - pvax - fvax) as of 29 September 2021 with a difference of 51. Not sure what other conditions in the linelist_death that makes the individual unvaccinated if any. Hope someone can clarify

**Comment by mnyunus** [comment]
I did a little calculation comparing daily unvaxxed deaths from both sources, and this is what I found (the highest differences). The DIFF column does add up to 51. So there is data inconsistency between both sources.

![screenshot-datastudio google com-2021 10 01-01_08_24](https://user-images.githubusercontent.com/89025874/135500361-6d5a1f8f-a4f0-4db8-9305-d6b397fbc5ca.png)

**Comment by MoH-Malaysia** [comment]
![image](https://user-images.githubusercontent.com/87315214/175791271-f24c5828-3729-4fa0-beb7-7c659759901f.png)

Not a mistake - it's due to some people inadvertently being vaccinated _after_ they tested positive but before they died. In short, they were unvaccinated at the time that they were infected.

These cases are rare, hence the small discrepancy.
